# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1424759009);
user_pref("app.update.lastUpdateTime.background-update-timer", 1424758769);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1424759129);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1424781335);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1424758889);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1424780249);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140923175406");
user_pref("browser.slowStartup.averageTime", 5935);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140923175406");
user_pref("browser.startup.homepage_override.mstone", "32.0.3");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1424785155628");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1424758473261");
user_pref("datareporting.policy.firstRunTime", "1424698755628");
user_pref("datareporting.sessions.current.activeTicks", 9);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1539);
user_pref("datareporting.sessions.current.main", 190);
user_pref("datareporting.sessions.current.sessionRestored", 1672);
user_pref("datareporting.sessions.current.startTime", "1424784900113");
user_pref("datareporting.sessions.current.totalTime", 45);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1424698745925,\"a\":2,\"t\":18,\"c\":true,\"m\":15,\"fp\":1735,\"sr\":11169}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1424758406512,\"a\":318,\"t\":26309,\"c\":true,\"m\":1875,\"fp\":5078,\"sr\":5279}");
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1424759011);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{22C7F6C6-8D67-4534-92B5-529A0EC09405}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Trend Micro\\\\OfficeScan Client\\\\FirefoxExtension\",\"mtime\":1424784871006,\"rdfTime\":1390889554000}}},{\"name\":\"app-global\",\"addons\":{\"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi\",\"mtime\":1405342340000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411995530491,\"rdfTime\":1411995530419}}}]");
user_pref("extensions.lastAppVersion", "32.0.3");
user_pref("extensions.lastPlatformVersion", "32.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140923175406");
user_pref("gecko.mstone", "32.0.3");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1424762915);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1424762916);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("security.disable_button.openCertManager", false);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1424762916);
user_pref("toolkit.startup.last_success", 1424784900);
user_pref("toolkit.telemetry.previousBuildID", "20140923175406");
