this._=this._||{};(function(_){var window=this;
try{
var da,ea,fa,ja,xa,ya;_.n=function(a){return function(){return _.aa[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.aa=[];da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};ea="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;
fa=function(a,b){if(b){for(var c=ea,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&da(c,d,{configurable:!0,writable:!0,value:f})}};ja=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
fa("String.prototype.repeat",function(a){return a?a:function(a){var b=ja(this,null,"repeat");if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}});fa("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=ja(this,a,"startsWith");a+="";for(var e=b.length,f=a.length,h=Math.max(0,Math.min(c|0,b.length)),k=0;k<f&&h<e;)if(b[h++]!=a[k++])return!1;return k>=f}});_.ka=_.ka||{};_.r=this;
_.ma=function(a){return void 0!==a};
_.oa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.pa=function(a){return"array"==_.oa(a)};_.t=function(a){return"string"==typeof a};_.sa="closure_uid_"+(1E9*Math.random()>>>0);xa=function(a,b,c){return a.call.apply(a.bind,arguments)};
ya=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?xa:ya;return _.u.apply(null,arguments)};_.za=Date.now||function(){return+new Date};
_.B=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.fL=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Da=window.osapi=window.osapi||{};_.google=window.google||{};window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

}catch(e){_._DumpException(e)}
try{
_.C=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.ma(b)?d[e]=b:d=d[e]?d[e]:d[e]={}};_.Fa=window;_.Ha=window.document;_.Ia=_.Fa.location;_.Ma=/\[native code\]/;_.Na=function(a,b,c){return a[b]=a[b]||c};_.Pa=function(){var a;if((a=Object.create)&&_.Ma.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Qa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}; _.Ra=function(a,b){a=a||{};for(var c in a)_.Qa(a,c)&&(b[c]=a[c])};_.Sa=_.Na(_.Fa,"gapi",{});
_.Ua=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Va=function(){return _.Fa.location.origin||_.Fa.location.protocol+"//"+_.Fa.location.host};
_.Xa=function(a,b,c){_.Wa(a,b,c,"add","at")};_.Wa=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Ya=_.Na(_.Fa,"___jsl",_.Pa());_.Na(_.Ya,"I",0);_.Na(_.Ya,"hel",10);var Za,$a,bb,cb,eb,fb;Za=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};$a=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};bb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};cb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!bb(a[c])&&!bb(b[c])?cb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=bb(b[c])?[]:{},cb(a[c],b[c])):a[c]=b[c])};
eb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
fb=function(a){$a(!0);var b=window.___gcfg,c=Za("cu");if(b&&b!==window.___gu){var d={};cb(d,b);c.push(d);window.___gu=b}var b=Za("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,Za("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=eb(f))&&b.push(f));a&&(d={},cb(d,a),c.push(d));d=Za("cd");a=0;for(b=d.length;a<b;++a)cb($a(),d[a]);d=Za("ci");a=0;for(b=d.length;a<b;++a)cb($a(),d[a]);a=0;for(b=c.length;a<b;++a)cb($a(),c[a])};_.D=function(a,b){if(!a)return $a();for(var c=a.split("/"),d=$a(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.gb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,h=e.length;f<h-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}fb(c)};
var hb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Na(_.Ya,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};hb&&hb();fb();_.C("gapi.config.get",_.D);_.C("gapi.config.update",_.gb);
}catch(e){_._DumpException(e)}
try{
_.Ti=window.gapi&&window.gapi.util||{};
}catch(e){_._DumpException(e)}
try{
var Ui=_.Ti=_.Ti||{};window.___jsl=window.___jsl||{};Ui.iC={Dha:function(){return window.___jsl.bsh},cN:function(){return window.___jsl.h},JH:function(a){window.___jsl.bsh=a},u7:function(a){window.___jsl.h=a}};
}catch(e){_._DumpException(e)}
try{
var Xi,Yi;Xi=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/u\/(\d)\//;Yi=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?\#]*)?\/b\/(\d{10,})\//;_.Zi=function(a){var b=_.D("googleapis.config/sessionIndex");null==b&&(b=window.__X_GOOG_AUTHUSER);if(null==b){var c=window.google;c&&(b=c.authuser)}null==b&&(a=a||window.location.href,b=_.Ua(a,"authuser")||null,null==b&&(b=(b=a.match(Xi))?b[1]:null));return null==b?null:String(b)};
_.$i=function(a){var b=_.D("googleapis.config/sessionDelegate");null==b&&(b=(a=(a||window.location.href).match(Yi))?a[1]:null);return null==b?null:String(b)};_.aj=function(a,b){var c=_.Zi(a)||b,d=_.$i(a),e="";c&&(e+="u/"+c+"/");d&&(e+="b/"+d+"/");return e||null};

}catch(e){_._DumpException(e)}
try{
_.bj=function(a){var b=String(a("immediate")||"");a=String(a("prompt")||"");return"true"===b||"none"===a};_.cj=function(a){return _.D("enableMultilogin")&&a("cookie_policy")&&!_.bj(a)?!0:!1};
_.dj=function(a,b,c){a=String(a);if(null!=(_.Ua(a,"authuser")||null)||null!=(_.Ua(a,"hd")||null))return a;b=_.Zi(b);if(c){var d=a,e=d.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(e&&e[0]){var f=e[1],h=e[4],k=e[5];e[3]=="/"+c&&(d=(f||"")+(h||"/")+(k||""))}if((e=d.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&e[0]){var f=e[2],l=e[4]||e[5],k=e[6];null!=b&&(d=(f||"")+"/"+c+"/"+(0,window.encodeURIComponent)(b)+(l||"/")+(k||""));return d}}null==
b?_.cj(function(b){return _.Ua(a,b)||null})||(l=(0,window.encodeURIComponent)("authuser")+"=0"):l=b.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)(String(b)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(b)].join(""):["authuser=",(0,window.encodeURIComponent)(b)].join("");c=a.split("#");b=c[0].indexOf("?");0>b?c[0]=[c[0],"?",l].join(""):(d=[c[0]],b<c[0].length-1&&d.push("&"),d.push(l),c[0]=d.join("")); return d=c.join("#")};_.google.Gia=_.dj;_.google.vE=_.Zi;_.google.Rha=_.$i;_.google.Sha=_.aj;

}catch(e){_._DumpException(e)}
try{
var ej=function(){this.Sk=-1};var gj=function(){this.Sk=64;this.yd=[];this.nC=[];this.bX=[];this.Qz=[];this.Qz[0]=128;for(var a=1;a<this.Sk;++a)this.Qz[a]=0;this.TA=this.Zp=0;this.reset()};_.B(gj,ej);gj.prototype.reset=function(){this.yd[0]=1732584193;this.yd[1]=4023233417;this.yd[2]=2562383102;this.yd[3]=271733878;this.yd[4]=3285377520;this.TA=this.Zp=0};
var hj=function(a,b,c){c||(c=0);var d=a.bX;if(_.t(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.yd[0];c=a.yd[1];for(var h=a.yd[2],k=a.yd[3],l=a.yd[4],m,e=0;80>e;e++)40>e?20>e?(f=k^c&(h^k),m=1518500249):(f=c^h^k,m=1859775393):60>e?(f=c&h|k&(c|h),m=2400959708):(f=c^h^k,m=3395469782),
f=(b<<5|b>>>27)+f+l+m+d[e]&4294967295,l=k,k=h,h=(c<<30|c>>>2)&4294967295,c=b,b=f;a.yd[0]=a.yd[0]+b&4294967295;a.yd[1]=a.yd[1]+c&4294967295;a.yd[2]=a.yd[2]+h&4294967295;a.yd[3]=a.yd[3]+k&4294967295;a.yd[4]=a.yd[4]+l&4294967295};
gj.prototype.update=function(a,b){if(null!=a){_.ma(b)||(b=a.length);for(var c=b-this.Sk,d=0,e=this.nC,f=this.Zp;d<b;){if(0==f)for(;d<=c;)hj(this,a,d),d+=this.Sk;if(_.t(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.Sk){hj(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.Sk){hj(this,e);f=0;break}}this.Zp=f;this.TA+=b}};
gj.prototype.digest=function(){var a=[],b=8*this.TA;56>this.Zp?this.update(this.Qz,56-this.Zp):this.update(this.Qz,this.Sk-(this.Zp-56));for(var c=this.Sk-1;56<=c;c--)this.nC[c]=b&255,b/=256;hj(this,this.nC);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.yd[c]>>d&255,++b;return a};
_.ij=function(){this.ir=new gj};_.g=_.ij.prototype;_.g.reset=function(){this.ir.reset()};_.g.uT=function(a){this.ir.update(a)};_.g.hM=function(){return this.ir.digest()};_.g.TI=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.uT(b)};_.g.Pi=function(){for(var a=this.hM(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

}catch(e){_._DumpException(e)}
try{
var sl,rl,yl,zl,tl,wl,ul,Al,vl,rl;_.xl=function(){var a;rl?(a=new _.Fa.Uint32Array(1),sl.getRandomValues(a),a=Number("0."+a[0])):(a=tl,a+=(0,window.parseInt)(ul.substr(0,20),16),ul=vl(ul),a/=wl+Math.pow(16,20));return a};sl=_.Fa.crypto;rl=!1;yl=0;zl=0;tl=1;wl=0;ul="";Al=function(a){a=a||_.Fa.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;tl=tl*b%wl;0<yl&&++zl==yl&&_.Wa(_.Fa,"mousemove",Al,"remove","de")};vl=function(a){var b=new _.ij;b.TI(a);return b.Pi()};
rl=!!sl&&"function"==typeof sl.getRandomValues;rl||(wl=1E6*(window.screen.width*window.screen.width+window.screen.height),ul=vl(_.Ha.cookie+"|"+_.Ha.location+"|"+(new Date).getTime()+"|"+Math.random()),yl=_.D("random/maxObserveMousemove")||0,0!=yl&&_.Xa(_.Fa,"mousemove",Al));

}catch(e){_._DumpException(e)}
try{
var Cl,El,Fl,Gl,Hl,Il,Jl,Kl,Ll,Nl,Ql,Rl,Sl,Tl,Ul,Vl;_.Bl=function(a,b){if(!a)throw Error(b||"");};Cl=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Dl=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;El=function(a,b){var c=[];if(a)for(var d in a)if(_.Qa(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};Fl=function(a){return a.fL+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.Xx.length?"#"+a.Xx.join("&"):"")};
Gl=function(a){a=a.match(Cl);var b=_.Pa();b.fL=a[1];b.query=a[3]?[a[3]]:[];b.Xx=a[5]?[a[5]]:[];return b};Hl=/'/g;Il=/"/g;Jl=/>/g;Kl=/</g;Ll=/&/g;_.Ml=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};Nl=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};
_.Ol=function(a,b){var c="";2E3<b.length&&(c=b.substring(2E3),b=b.substring(0,2E3));var d=a.createElement("div"),e=a.createElement("a");e.href=b;d.appendChild(e);d.innerHTML=d.innerHTML;b=String(d.firstChild.href);d.parentNode&&d.parentNode.removeChild(d);return b+c};_.Pl=function(a,b,c,d){a=Gl(a);a.query.push.apply(a.query,El(b,d));a.Xx.push.apply(a.Xx,El(c,d));return Fl(a)};
Ql=function(a){return String(a).replace(Ll,"&amp;").replace(Kl,"&lt;").replace(Jl,"&gt;").replace(Il,"&quot;").replace(Hl,"&#39;")};Sl=function(){var a=_.Ya.onl;if(!a){a=_.Pa();_.Ya.onl=a;var b=_.Pa();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};Tl=function(a,b){var c=b.onload;return"function"===typeof c?(Sl().a(a,c),c):null}; Ul=function(a){_.Bl(/^\w+$/.test(a),"Unsupported id - "+a);Sl();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};Vl=function(a){Sl().r(a)};
var Xl,Yl,bm;_.Wl={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};Xl={allowtransparency:!0,onload:!0};Yl=0;_.Zl=function(a,b){var c,d=0;do c=b.id||["I",Yl++,"_",(new Date).getTime()].join("");while(a.getElementById(c)&&5>++d);_.Bl(5>d,"Error creating iframe id");return c};_.$l=function(a,b){return a?b+"/"+a:""};
_.am=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Ra(d.queryParams||{},e);_.Ra(d.fragmentParams||{},f);var h=d.connectWithQueryParams?e:f,k=d.pfname,l=_.Pa();l.id=c;l.parent=a.location.protocol+"//"+a.location.host;c=_.Ua(a.location.href,"parent");k=k||"";!k&&c&&(k=_.$l(_.Ua(a.location.href,"id",""),_.Ua(a.location.href,"pfname","")));l.pfname=k;_.Ra(l,h);(l=_.Ua(b,"rpctoken")||e.rpctoken||f.rpctoken)||(l=h.rpctoken=d.rpctoken||String(Math.round(1E8*
_.xl())));d.rpctoken=l;h=a.location.href;a=_.Pa();(l=_.Ua(h,"_bsh",_.Ya.bsh))&&(a._bsh=l);(h=_.Ya.dpo?_.Ya.h:_.Ua(h,"jsh",_.Ya.h))&&(a.jsh=h);d.hintInFragment?_.Ra(a,f):_.Ra(a,e);return _.Pl(b,e,f,d.paramsSerializer)};bm=function(a){_.Bl(!a||_.Dl.test(a),"Illegal url for new iframe - "+a)};
_.cm=function(a,b,c,d,e){bm(c.src);var f,h=Tl(d,c),k=h?Ul(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+Ql(String(c.frameborder))+'" scrolling="'+Ql(String(c.scrolling))+'" '+k+' name="'+Ql(String(c.name))+'"/>'))}catch(m){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},Vl(d)))}for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.Ra(a,f.style):Xl[l]||f.setAttribute(l,String(a));(l=e&&e.beforeNode||null)||e&&e.dontclear|| Nl(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var dm,gm;dm=/^:[\w]+$/;_.em=/:([a-zA-Z_]+):/g;_.fm=function(){var a=_.Zi()||"0",b=_.$i(),c=_.aj(void 0,a),d=!1===_.D("isLoggedIn"),e=d?"_/im/":"";e&&(c="");var f=_.D("iframes/:socialhost:"),h=_.D("iframes/:im_socialhost:");return Rl={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};gm=function(a,b){return _.fm()[b]||""};_.hm=function(a){return _.Ol(_.Ha,a.replace(_.em,gm))};
_.im=function(a){var b=a;dm.test(a)&&(b=_.D("iframes/"+b.substring(1)+"/url"),_.Bl(!!b,"Unknown iframe url config for - "+a));return _.hm(b)};
_.jm=function(a,b,c){var d=c||{};c=d.attributes||{};_.Bl(!d.allowPost||!c.onload,"onload is not supported by post iframe");a=_.im(a);c=b.ownerDocument||_.Ha;var e=_.Zl(c,d);a=_.am(c,a,e,d);var f=_.Pa();_.Ra(_.Wl,f);_.Ra(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;if((d||{}).allowPost&&2E3<a.length){var h=Gl(a);f.src="";f["data-postorigin"]=a;a=_.cm(c,b,f,e);var k;if(-1!=window.navigator.userAgent.indexOf("WebKit")){k=a.contentWindow.document;k.open();var f=k.createElement("div"),l={},m=e+"_inner";
l.name=m;l.src="";l.style="display:none";_.cm(c,f,l,m,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(l=0;l<f.length;l++)m=f[l].split("=",2),d.push([(0,window.decodeURIComponent)(m[0]),(0,window.decodeURIComponent)(m[1])]);h.query=[];f=Fl(h);_.Bl(_.Dl.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type="hidden",f.name=d[e][0],f.value=d[e][1],h.appendChild(f);b.appendChild(h);h.submit(); h.parentNode.removeChild(h);k&&k.close();b=a}else b=_.cm(c,b,f,e,d);return b};

}catch(e){_._DumpException(e)}
try{
_.Vi=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a)throw Error("b");var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e|| "https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

}catch(e){_._DumpException(e)}
try{
_.Ti.nb=function(a){return _.Vi(a)};
}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};
}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};_.E.rz=function(a,b,c){for(var d=[],e=2,f=arguments.length;e<f;++e)d.push(arguments[e]);return function(){for(var c=d.slice(),e=0,f=arguments.length;e<f;++e)c.push(arguments[e]);return b.apply(a,c)}};_.E.Nu=function(a){var b,c,d={};for(b=0;c=a[b];++b)d[c]=c;return d};

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};
(function(){function a(a,b){return String.fromCharCode(b)}var b={0:!1,10:!0,13:!0,34:!0,39:!0,60:!0,62:!0,92:!0,8232:!0,8233:!0,65282:!0,65287:!0,65308:!0,65310:!0,65340:!0};_.E.escape=function(a,b){if(a){if("string"===typeof a)return _.E.Sx(a);if("Array"===typeof a)for(var c=0,d=a.length;c<d;++c)a[c]=_.E.escape(a[c]);else if("object"===typeof a&&b){c={};for(d in a)a.hasOwnProperty(d)&&(c[_.E.Sx(d)]=_.E.escape(a[d],!0));return c}}return a};_.E.Sx=function(a){if(!a)return a;for(var c=[],e,f,h=0,k= a.length;h<k;++h)e=a.charCodeAt(h),f=b[e],!0===f?c.push("&#",e,";"):!1!==f&&c.push(a.charAt(h));return c.join("")};_.E.pja=function(b){return b?b.replace(/&#([0-9]+);/g,a):b}})();

}catch(e){_._DumpException(e)}
try{
_.ql=_.ql||{};_.ql.t0=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

}catch(e){_._DumpException(e)}
try{
_.ql=_.ql||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.ql.Td=function(){var b=_.ql.t0().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift(),d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight)var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom"),b=Math.max(b,h);c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

}catch(e){_._DumpException(e)}
try{
(function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Ba=function(b){a(2,b)};_.Ca=function(b){a(3,b)};_.kb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b})();

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};(function(){var a=[];_.E.Jia=function(b){a.push(b)};_.E.Yia=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
}catch(e){_._DumpException(e)}
try{
_.lb=function(a){return!!a&&"object"===typeof a&&_.Ma.test(a.push)};_.mb=function(a,b){var c=_.Na(_.Ya,"watt",_.Pa());_.Na(c,a,b)};_.E=_.E||{};
(function(){var a=null;_.E.Uc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.E.Uc()})();
_.C("gadgets.util.getUrlParameters",_.E.Uc);
}catch(e){_._DumpException(e)}
try{
_.pb=window.console;_.qb=function(a){_.pb&&_.pb.log&&_.pb.log(a)};_.rb=function(){};
}catch(e){_._DumpException(e)}
try{
_.vb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.gb(a());return{register:function(a,c,d){d&&d(_.D())},get:function(a){return _.D(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.gb(a)},Mc:function(){}}}();
_.C("gadgets.config.register",_.vb.register);_.C("gadgets.config.get",_.vb.get);_.C("gadgets.config.init",_.vb.Mc);_.C("gadgets.config.update",_.vb.update);
}catch(e){_._DumpException(e)}
try{
var wb=function(a){return 10>a?"0"+a:a},xb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},zb=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=xb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(zb(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Qa(a,c)&&"string"===typeof c&&(d=zb(a[c]))&&b.push(zb(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Ab=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},Bb=!1,Cb;try{Bb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}Cb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Db=Bb?window.JSON.stringify:zb;_.Fb=Bb?Cb:Ab;Cb||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",wb(this.getUTCMonth()+1),"-",wb(this.getUTCDate()),"T",wb(this.getUTCHours()),":",wb(this.getUTCMinutes()),":",wb(this.getUTCSeconds()),"Z"].join("")});

}catch(e){_._DumpException(e)}
try{
_.C("gadgets.json.stringify",_.Db);_.C("gadgets.json.parse",_.Fb);_.Ua(_.Fa.location.href,"rpctoken")&&_.Xa(_.Ha,"unload",function(){});
}catch(e){_._DumpException(e)}
try{
var Ib;_.Gb=function(){var a=_.Ha.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Hb=function(a){if(_.Gb())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Fa.addEventListener?(_.Fa.addEventListener("load",c,!1),_.Fa.addEventListener("DOMContentLoaded",c,!1)):_.Fa.attachEvent&&(_.Fa.attachEvent("onreadystatechange",function(){_.Gb()&&c.apply(this,arguments)}),_.Fa.attachEvent("onload",c))}};Ib=Ib||{};Ib.rR=null; Ib.OP=null;Ib.Py=null;Ib.frameElement=null;
Ib=Ib||{};
Ib.mJ||(Ib.mJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Fb)(a.data);if(b&&b.f){(0,_.kb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.xl(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ca("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Dp:function(){return"wpm"},q3:function(){return!0},Mc:function(f,h){_.vb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},wd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.xl(a),e=_.G.GK(a);d?window.setTimeout(function(){var a=(0,_.Db)(c);(0,_.kb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ca("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
Ib=Ib||{};
Ib.Wx||(Ib.Wx=function(){function a(a,b){J[b]=J[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+A+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++z;null!==w&&(null!==v||50<=z)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){M[".."]||(k(".."),y++,50<=y&&null!==F?(window.clearTimeout(F),F=null):F=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<x.length;){var a=x.shift(),b=a.t8;v.setup(a.Ar,".."===b?_.G.DB:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){M[".."]||null!==
F||(F=window.setTimeout(c,100))}function f(a,b,c){b=_.G.xl(a);var d=_.G.ll(a);v["sendMessage_"+(".."===a?_.G.DB:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.Db)(c),b);return!0}function h(a,b){var c=(0,_.Fb)(a),d=c._scr;d?(q(d,!0),M[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){p(c,b)},0)}function k(a,b){var c=_.G.DB,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,p=null,q=null,v=null,x=[],w=null,z=0,y=0,F=null,M={},A=window.location.protocol+"//"+window.location.host,J;window.___jsl=
window.___jsl||{};J=window.___jsl._fm={};_.vb.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(h,"receiveMessage");return{Dp:function(){return"flash"},q3:function(){return!0},Mc:function(a,b){p=a;q=b;return m=!0},wd:function(a,c){x.push({Ar:c,t8:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,hX:h,Uga:d,Vga:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.XQ=_.G.registerDefault,_.G.sT=_.G.unregisterDefault,_.G.MM=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.Qt=_.G.getRelayUrl,_.G.pj=_.G.setRelayUrl,_.G.xA=_.G.setAuthToken,_.G.Hv=_.G.setupReceiver,_.G.ll=_.G.getAuthToken,_.G.bH=_.G.removeReceiver,_.G.rN=_.G.getRelayChannel,_.G.gA=_.G.receive,_.G.TQ=_.G.receiveSameDomain,_.G.nb=
_.G.getOrigin,_.G.xl=_.G.getTargetOrigin,_.G.GK=_.G._getTargetWin,_.G.gX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!na[a]){var c=Z;b||(c=Ja);na[a]=c;for(var d=qa[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=M[a];c.call(a,f.f,f)}qa[a]=[]}}function b(){function a(){ba=!0}X||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),X=!0)}function c(a,c,d,e,f){M[c]&&M[c]===d||(_.Ca("Invalid gadgets.rpc token. "+
M[c]+" vs "+d),Ga(c,2));f.onunload=function(){L[c]&&!ba&&(Ga(c,1),_.G.bH(c))};b();e=(0,_.Fb)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(M[b.f]&&M[b.f]!==b.t&&(_.Ca("Invalid gadgets.rpc token. "+M[b.f]+" vs "+b.t),Ga(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(ha){}f&&
h==d||(f=c);b.referer=f}d=(z[b.s]||z[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.G.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==L[a]){"undefined"===typeof L[a]&&(L[a]=0);var c=h(a);".."!==a&&null==c||!0!==Z.wd(a,b)?!0!==L[a]&&10>L[a]++?window.setTimeout(function(){k(a,b)},500):(na[a]=Ja,L[a]=!0):L[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(F[a]=!!c)}function p(a,b){b=b||"";M[a]=String(b);k(a,b)}function q(a){a=(a.passReferrer||"").split(":",2);La=a[0]||"none";ca=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(Z=Ib.Py||Ja,Z.Mc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};q(c);var d=c.parentRelayUrl||"",d=e(W.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
v(c);p("..",a)}!W.parent&&b?c({}):_.vb.register("rpc",null,c)}function w(a,b,c){if(".."===a)x(c||W.rpctoken||W.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.E)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.nb(d);m(a,b);b=_.E.Uc(d);p(a,c||b.rpctoken)}}var z={},y={},F={},M={},A=0,J={},L={},W={},na={},qa={},La=null,ca=null,Y=window.top!==window.self,wa=window.name,Ga=function(){},ra=window.console,Ea=ra&&ra.log&&function(a){ra.log(a)}||function(){},
Ja=function(){function a(a){return function(){Ea(a+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.E&&(W=_.E.Uc());var ba=!1,X=!1,Z=function(){if("flash"==W.rpctx)return Ib.Wx;if("rmr"==W.rpctx)return Ib.rR;var a="function"===typeof window.postMessage?Ib.mJ:"object"===typeof window.postMessage?Ib.mJ:window.ActiveXObject?Ib.Wx?Ib.Wx:Ib.OP?Ib.OP:Ib.Py:0<window.navigator.userAgent.indexOf("WebKit")?
Ib.rR:"Gecko"===window.navigator.product?Ib.frameElement:Ib.Py;a||(a=Ja);return a}();z[""]=function(){Ea("Unknown RPC service: "+this.s)};z.__cb=function(a,b){var c=J[a];c&&(delete J[a],c.call(this,b))};return{config:function(a){"function"===typeof a.zR&&(Ga=a.zR)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");z[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete z[a]},XQ:function(a){z[""]=a},sT:function(){delete z[""]},
MM:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=wa:"/"==a.charAt(0)&&(e=_.G.nb(window.location.href),e="/"+wa+(e?"|"+e:""));++A;c&&(J[A]=c);var h={s:b,f:e,c:c?A:0,a:Array.prototype.slice.call(arguments,3),t:M[a],l:!!F[a]},k;a:if("bidir"===La||"c2p"===La&&".."===a||"p2c"===La&&".."!==a){k=window.location.href;var l="?";if("query"===ca)l="#";else if("hash"===ca)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
na[a])||null===f(a)||(k=Z),0===b.indexOf("legacy__")&&(k=Z,h.s=b.substring(8),h.c=h.c?h.c:A),h.g=!0,h.r=e,k?(F[a]&&(k=Ib.Py),!1===k.call(a,e,h)&&(na[a]=Ja,Z.call(a,e,h))):qa[a]?qa[a].push(h):qa[a]=[h]},Qt:l,pj:m,xA:p,Hv:w,ll:function(a){return M[a]},bH:function(a){delete y[a];delete F[a];delete M[a];delete L[a];delete na[a]},rN:function(){return Z.Dp()},gA:function(a,b){4<a.length?Z.hX(a,d):c.apply(null,a.concat(b))},TQ:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},nb:e,xl:function(a){var b=l(a);a=b?b:(b=f(a))?b.origin:".."==a?W.parent:window.document.getElementById(a).src;return e(a)},Mc:function(){!1===Z.Mc(d,a)&&(Z=Ja);Y?w(".."):_.vb.register("rpc",null,function(a){a=a.rpc||{};q(a);v(a)})},GK:h,gX:f,l9:"__ack",DB:wa||"..",Sea:0,Rea:1,Qea:2}}();_.G.Mc()};
_.G.config({zR:function(a){throw Error("h`"+a);}});_.kb=_.rb;_.C("gadgets.rpc.config",_.G.config);_.C("gadgets.rpc.register",_.G.register);_.C("gadgets.rpc.unregister",_.G.unregister);_.C("gadgets.rpc.registerDefault",_.G.XQ);_.C("gadgets.rpc.unregisterDefault",_.G.sT);_.C("gadgets.rpc.forceParentVerifiable",_.G.MM);_.C("gadgets.rpc.call",_.G.call);_.C("gadgets.rpc.getRelayUrl",_.G.Qt);_.C("gadgets.rpc.setRelayUrl",_.G.pj);_.C("gadgets.rpc.setAuthToken",_.G.xA);_.C("gadgets.rpc.setupReceiver",_.G.Hv);_.C("gadgets.rpc.getAuthToken",_.G.ll); _.C("gadgets.rpc.removeReceiver",_.G.bH);_.C("gadgets.rpc.getRelayChannel",_.G.rN);_.C("gadgets.rpc.receive",_.G.gA);_.C("gadgets.rpc.receiveSameDomain",_.G.TQ);_.C("gadgets.rpc.getOrigin",_.G.nb);_.C("gadgets.rpc.getTargetOrigin",_.G.xl);

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};_.E.Rw=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Ba("cannot attachBrowserEvent: "+b)};_.E.X5=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Ba("cannot removeBrowserEvent: mousemove")};

}catch(e){_._DumpException(e)}
try{
_.Zj=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;p=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,q,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),q=1518500249):(m=d^f^k,q=1859775393):60>c?(m=d&f|k&(d|f),q=2400959708):(m=d^f^k,q=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+q+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64;for(;d<c;)if(f[m++]=a[d++],p++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64}function d(){var a=[],
d=8*p;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,p;a();return{reset:a,update:c,digest:d,Pi:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.ak=function(){function a(a){var b=_.Zj();b.update(a);return b.Pi()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.D("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,h=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%h;0<c&&++d==c&&_.E.X5(k)};0!=c&&_.E.Rw(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(h+Math.pow(16,20))}}();
_.C("shindig.random",_.ak);
}catch(e){_._DumpException(e)}
try{
_.H={};_.tc={};window.iframer=_.tc;
}catch(e){_._DumpException(e)}
try{
_.H.Ua=_.H.Ua||{};_.H.Ua.UX=function(a){try{return!!a.document}catch(b){}return!1};_.H.Ua.CN=function(a){var b=a.parent;return a!=b&&_.H.Ua.UX(b)?_.H.Ua.CN(b):a};_.H.Ua.$ha=function(a){var b=a.userAgent||"";a=a.product||"";return 0!=b.indexOf("Opera")&&-1==b.indexOf("WebKit")&&"Gecko"==a&&0<b.indexOf("rv:1.")};

}catch(e){_._DumpException(e)}
try{
var Lq,Mq,Nq,Pq,Qq,Rq,Wq,Xq,Yq,Zq,ar,br,cr,er,fr,gr;Lq=function(){_.H.zO++;return["I",_.H.zO,"_",(new Date).getTime()].join("")};Mq=function(a){return a instanceof Array?a.join(","):a instanceof Object?(0,_.Db)(a):a};Nq=function(){};Pq=function(a){a&&a.match(Oq)&&_.gb("googleapis.config/gcv",a)};Qq=function(a){_.Ti.iC.u7(a)};Rq=function(a){_.Ti.iC.JH(a)};_.Sq=function(a,b){var c=b||{},d;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);return c};
_.Uq=function(a,b,c,d,e){var f=[],h;for(h in a)if(a.hasOwnProperty(h)){var k=b,l=c,m=a[h],p=d,q=Tq(h);q[k]=q[k]||{};p=_.E.rz(p,m);m._iframe_wrapped_rpc_&&(p._iframe_wrapped_rpc_=!0);q[k][l]=p;f.push(h)}if(e)for(h in _.H.Op)_.H.Op.hasOwnProperty(h)&&f.push(h);return f.join(",")};Wq=function(a,b,c){var d={};if(a&&a._methods){a=a._methods.split(",");for(var e=0;e<a.length;e++){var f=a[e];d[f]=Vq(f,b,c)}}return d};
Xq=function(a){if(a&&a.disableMultiLevelParentRelay)a=!1;else{var b;if(b=_.tc&&_.tc._open&&"inline"!=a.style&&!0!==a.inline)a=a.container,b=!(a&&("string"==typeof a&&window.document.getElementById(a)||window.document==(a.ownerDocument||a.document)));a=b}return a};Yq=function(a,b){var c={},d=b.params||{},e;for(e in a)"#"==e.charAt(0)&&(c[e.substring(1)]=a[e]),0==e.indexOf("fr-")&&(c[e.substring(3)]=a[e]),"#"==d[e]&&(c[e]=a[e]);for(var f in c)delete a["fr-"+f],delete a["#"+f],delete a[f];return c};
Zq=function(a){if(":"==a.charAt(0)){var b=_.D("iframes/"+a.substring(1));a={};_.Ra(b,a);(b=a.url)&&(a.url=_.hm(b));a.params||(a.params={});return a}return{url:_.hm(a)}};ar=function(a){function b(){}b.prototype=$q.prototype;a.prototype=new b};br=function(a){return _.H.Vv[a]};cr=function(a,b){_.H.Vv[a]=b};er=function(a){a=a||{};"auto"===a.height&&(a.height=_.ql.Td());var b=window&&dr&&dr.ya();b?b.mR(a.width||0,a.height||0):_.tc&&_.tc._resizeMe&&_.tc._resizeMe(a)};fr=function(a){Pq(a)};
gr=function(a){var b=_.Ua(a.location.href,"urlindex");if(b=_.Na(_.Ya,"fUrl",[])[b]){var c=a.location.hash,b=b+(/#/.test(b)?c.replace(/^#/,"&"):c);a.location.replace(b)}};
if(window.ToolbarApi)dr=window.ToolbarApi,dr.ya=window.ToolbarApi.getInstance,dr.prototype=window.ToolbarApi.prototype,_.g=dr.prototype,_.g.openWindow=dr.prototype.openWindow,_.g.BL=dr.prototype.closeWindow,_.g.nS=dr.prototype.setOnCloseHandler,_.g.qL=dr.prototype.canClosePopup,_.g.mR=dr.prototype.resizeWindow;else{var dr=function(){},hr=null;dr.ya=function(){!hr&&window.external&&window.external.GTB_IsToolbar&&(hr=new dr);return hr};_.g=dr.prototype;_.g.openWindow=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.g.BL=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.g.nS=function(a,b){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,b)};_.g.qL=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.g.mR=function(a,b){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,b)};window.ToolbarApi=dr;window.ToolbarApi.getInstance=dr.ya};
var ir=function(){_.G.register("_noop_echo",function(){this.callback(_.H.V_(_.H.Dl[this.f]))})},jr=function(){window.setTimeout(function(){_.G.call("..","_noop_echo",_.H.k5)},0)},Vq=function(a,b,c){var d=function(d){var e=Array.prototype.slice.call(arguments,0),h=e[e.length-1];if("function"===typeof h){var k=h;e.pop()}e.unshift(b,a,k,c);_.G.call.apply(_.G,e)};d._iframe_wrapped_rpc_=!0;return d},Tq=function(a){_.H.iA[a]||(_.H.iA[a]={},_.G.register(a,function(b,c){var d=this.f;if(!("string"!=typeof b||
b in{}||d in{})){var e=this.callback,f=_.H.iA[a][d],h;f&&Object.hasOwnProperty.call(f,b)?h=f[b]:Object.hasOwnProperty.call(_.H.Op,a)&&(h=_.H.Op[a]);if(h)return d=Array.prototype.slice.call(arguments,1),h._iframe_wrapped_rpc_&&e&&d.push(e),h.apply({},d)}_.Ca(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',b,'" from frame "',d,'".'].join(""));return null}));return _.H.iA[a]};
_.H.QX=function(a,b,c){var d=Array.prototype.slice.call(arguments);_.H.nN(function(a){a.sameOrigin&&(d.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.G.call.apply(_.G,d))})};_.H.S5=function(a,b){_.G.register(a,b)};
var Oq=/^[-_.0-9A-Za-z]+$/,kr={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"},lr={onBeforeParentOpen:"beforeparentopen"},mr={onOpen:function(a){var b=a.uc();a.Gg(b.container||b.element);return a},onClose:function(a){a.remove()}};_.H.Fp=function(a){var b=_.Pa();_.Ra(_.Wl,b);_.Ra(a,b);return b};
var $q=function(a,b,c,d,e,f,h,k){this.config=Zq(a);this.openParams=this.$u=b||{};this.params=c||{};this.methods=d;this.MA=!1;nr(this,b.style);this.Es={};qr(this,function(){var a;(a=this.$u.style)&&_.H.Vv[a]?a=_.H.Vv[a]:a?(_.Ba(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=null):a=mr;if(a){var b;if("function"===typeof a)b=a(this);else{var c={};for(b in a){var d=a[b];c[b]="function"===typeof d?_.E.rz(a,d,this):d}b=c}for(var h in e)a=b[h],"function"===typeof a&&
rr(this,e[h],_.E.rz(b,a))}f&&rr(this,"close",f)});this.hk=this.ac=h;this.sG=(k||[]).slice();h&&this.sG.unshift(h.Aa())};$q.prototype.uc=function(){return this.$u};$q.prototype.Ti=function(){return this.params};$q.prototype.ny=function(){return this.methods};$q.prototype.Hd=function(){return this.hk};var nr=function(a,b){if(!a.MA){var c=b&&!_.H.Vv[b]&&_.H.aD[b];c?(a.$C=[],c(function(){a.MA=!0;for(var b=0,c=a.$C.length;b<c;++b)a.$C[b].call(a)})):a.MA=!0}},qr=function(a,b){a.MA?b.call(a):a.$C.push(b)};
$q.prototype.Pd=function(a,b){qr(this,function(){rr(this,a,b)})};var rr=function(a,b,c){a.Es[b]=a.Es[b]||[];a.Es[b].push(c)};$q.prototype.io=function(a,b){qr(this,function(){var c=this.Es[a];if(c)for(var d=0,e=c.length;d<e;++d)if(c[d]===b){c.splice(d,1);break}})};
$q.prototype.ci=function(a,b){var c,d=this.Es[a];if(d)for(var e=Array.prototype.slice.call(arguments,1),f=0,h=d.length;f<h;++f)try{c=d[f].apply({},e)}catch(k){_.Ca(['Exception when calling callback "',a,'" with exception "',k.name,": ",k.message,'".'].join(""))}return c};
var sr=function(a){return"number"==typeof a?{value:a,VD:a+"px"}:"100%"==a?{value:100,VD:"100%",bP:!0}:null},tr=function(a,b,c,d,e,f,h){$q.call(this,a,b,c,d,kr,e,f,h);this.id=b.id||Lq();this.vv=b.rpctoken&&String(b.rpctoken)||Math.round(1E9*(0,_.ak)());this.r2=Yq(this.params,this.config);this.LD={};qr(this,function(){this.ci("open");_.Sq(this.LD,this)})};ar(tr);_.g=tr.prototype;
_.g.Gg=function(a,b){if(!this.config.url)return _.Ca("Cannot open iframe, empty URL."),this;var c=this.id;_.H.Dl[c]=this;var d=_.Sq(this.methods);d._ready=this.Mz;d._close=this.close;d._open=this.Nz;d._resizeMe=this.Jq;d._renderstart=this.hQ;var e=this.r2;this.vv&&(e.rpctoken=this.vv);e._methods=_.Uq(d,c,"",this,!0);this.Gx=a="string"===typeof a?window.document.getElementById(a):a;d={};d.id=c;if(b){d.attributes=b;var f=b.style;if("string"===typeof f){var h;if(f){h=[];for(var f=f.split(";"),k=0,l=
f.length;k<l;++k){var m=f[k];if(0!=m.length||k+1!=l)m=m.split(":"),2==m.length&&m[0].match(/^[ a-zA-Z_-]+$/)&&m[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?h.push(m.join(":")):_.Ca(['Iframe style "',f[k],'" not allowed.'].join(""))}h=h.join(";")}else h="";b.style=h}}this.uc().allowPost&&(d.allowPost=!0);d.queryParams=this.params;d.fragmentParams=e;d.paramsSerializer=Mq;this.ki=_.jm(this.config.url,a,d);e=this.ki.getAttribute("data-postorigin")||this.ki.src;_.H.Dl[c]=this;_.G.xA(this.id,this.vv);_.G.pj(this.id,
e);return this};_.g.qf=function(a,b){this.LD[a]=b};_.g.Aa=function(){return this.id};_.g.Xa=function(){return this.ki};_.g.Ib=function(){return this.Gx};_.g.cg=function(a){this.Gx=a};_.g.Mz=function(a){var b=Wq(a,this.id,"");this.hk&&"function"==typeof this.methods._ready&&(a._methods=_.Uq(b,this.hk.Aa(),this.id,this,!1),this.methods._ready(a));_.Sq(a,this);_.Sq(b,this);this.ci("ready",a)};_.g.hQ=function(a){this.ci("renderstart",a)};
_.g.close=function(a){a=this.ci("close",a);delete _.H.Dl[this.id];return a};_.g.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.g.Nz=function(a){var b=Wq(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Gx);if(Xq(a.openParams))new ur(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain);else{var c=new tr(a.url,a.openParams,a.params,b,b._onclose,this,a.openedByProxyChain),d=this;qr(c,function(){var a={childId:c.Aa()},f=c.LD;f._toclose=c.close;a._methods=_.Uq(f,d.id,c.id,c,!1);b._onopen(a)})}};
_.g.Jq=function(a){if(void 0===this.ci("resize",a)&&this.ki){var b=sr(a.width);null!=b&&(this.ki.style.width=b.VD);a=sr(a.height);null!=a&&(this.ki.style.height=a.VD);this.ki.parentElement&&(null!=b&&b.bP||null!=a&&a.bP)&&(this.ki.parentElement.style.display="block")}};
var ur=function(a,b,c,d,e,f,h){$q.call(this,a,b,c,d,lr,e,f,h);this.url=a;this.Ho=null;this.RG=Lq();qr(this,function(){var a;this.ci("beforeparentopen");var b=_.Sq(this.methods);b._onopen=this.b5;b._ready=this.Mz;b._onclose=this.a5;this.params._methods=_.Uq(b,"..",this.RG,this,!0);b={};for(a in this.params)b[a]=Mq(this.params[a]);var c=this.config.url;if(this.$u.hideUrlFromParent){a=window.name;var d=c,c=_.Pl(this.config.url,this.params,{},Mq),e=b,b={};b._methods=e._methods;b["#opener"]=e["#opener"];
b["#urlindex"]=e["#urlindex"];b["#opener"]&&void 0!=e["#urlindex"]?(b["#opener"]=a+","+b["#opener"],a=d):(d=_.Na(_.Ya,"fUrl",[]),e=d.length,d[e]=c,_.Ya.rUrl=gr,b["#opener"]=a,b["#urlindex"]=e,a=_.Ti.nb(_.Fa.location.href),c=_.D("iframes/relay_url_"+(0,window.encodeURIComponent)(a))||"/_/gapi/sibling/1/frame.html",a+=c);c=a}_.tc._open({url:c,openParams:this.$u,params:b,proxyId:this.RG,openedByProxyChain:this.sG})})};ar(ur);ur.prototype.n0=function(){return this.Ho};
ur.prototype.b5=function(a){this.Ho=a.childId;var b=Wq(a,"..",this.Ho);_.Sq(b,this);this.close=b._toclose;_.H.Dl[this.Ho]=this;this.hk&&this.methods._onopen&&(a._methods=_.Uq(b,this.hk.Aa(),this.Ho,this,!1),this.methods._onopen(a))};ur.prototype.Mz=function(a){var b=String(this.Ho),c=Wq(a,"..",b);_.Sq(a,this);_.Sq(c,this);this.ci("ready",a);this.hk&&this.methods._ready&&(a._methods=_.Uq(c,this.hk.Aa(),b,this,!1),this.methods._ready(a))};
ur.prototype.a5=function(a){if(this.hk&&this.methods._onclose)this.methods._onclose(a);else return a=this.ci("close",a),delete _.H.Dl[this.Ho],a};
var vr=function(a,b,c,d,e,f,h){$q.call(this,a,b,c,d,lr,f,h);this.id=b.id||Lq();this.z8=e;d._close=this.close;this.onClosed=this.VP;this.KT=0;qr(this,function(){this.ci("beforeparentopen");var b=_.Sq(this.methods);this.params._methods=_.Uq(b,"..",this.RG,this,!0);b={};b.queryParams=this.params;a=_.am(_.Ha,this.config.url,this.id,b);var c=e.openWindow(a);this.canAutoClose=function(a){a(e.qL(c))};e.nS(c,this);this.KT=c})};ar(vr);
vr.prototype.close=function(a){a=this.ci("close",a);this.z8.BL(this.KT);return a};vr.prototype.VP=function(){this.ci("close")};
(function(){_.H.Dl={};_.H.Vv={};_.H.aD={};_.H.zO=0;_.H.iA={};_.H.Op={};_.H.Sz=null;_.H.Rz=[];_.H.k5=function(a){var b=!1;try{if(null!=a)var c=window.parent.frames[a.id],b=c.iframer.id==a.id&&c.iframes.openedId_(_.tc.id)}catch(f){}try{_.H.Sz={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:b};for(a=0;a<_.H.Rz.length;++a)_.H.Rz[a](_.H.Sz);_.H.Rz=[]}catch(f){}};_.H.V_=function(a){var b=a&&a.hk,c=null;b&&(c={},c.id=b.Aa(),c.proxyChain=
a.sG);return c};ir();if(window.parent!=window){var a=_.E.Uc();a.gcv&&Pq(a.gcv);var b=a.jsh;b&&Qq(b);_.Sq(Wq(a,"..",""),_.tc);_.Sq(a,_.tc);jr()}_.H.Sa=br;_.H.Fc=cr;_.H.t7=fr;_.H.resize=er;_.H.c_=function(a){return _.H.aD[a]};_.H.MH=function(a,b){_.H.aD[a]=b};_.H.lR=er;_.H.M7=fr;_.H.Iy={};_.H.Iy.get=br;_.H.Iy.set=cr;_.H.nX=function(a,b){Tq(a);_.H.Op[a]=b||window[a]};_.H.tha=function(a){delete _.H.Op[a]};_.H.open=function(a,b,e,f,h,k){3==arguments.length?f={}:4==arguments.length&&"function"===typeof f&&
(h=f,f={});var c="bubble"===b.style&&dr?dr.ya():null;return c?new vr(a,b,e,f,c,h,k):Xq(b)?new ur(a,b,e,f,h,k):new tr(a,b,e,f,h,k)};_.H.close=function(a,b){_.tc&&_.tc._close&&_.tc._close(a,b)};_.H.ready=function(a,b,e){2==arguments.length&&"function"===typeof b&&(e=b,b={});var c=a||{};"height"in c||(c.height=_.ql.Td());c._methods=_.Uq(b||{},"..","",_.tc,!0);_.tc&&_.tc._ready&&_.tc._ready(c,e)};_.H.nN=function(a){_.H.Sz?a(_.H.Sz):_.H.Rz.push(a)};_.H.e5=function(a){return!!_.H.Dl[a]};_.H.n_=function(){return["https://ssl.gstatic.com/gb/js/",
_.D("googleapis.config/gcv")].join("")};_.H.MQ=function(a){var b={mouseover:1,mouseout:1};if(_.tc._event)for(var c=0;c<a.length;c++){var f=a[c];f in b&&_.E.Rw(window.document,f,function(a){_.tc._event({event:a.type,timestamp:(new Date).getTime()})},!0)}};_.H.A7=Qq;_.H.JH=Rq;_.H.rP=Nq;_.H.BO=_.tc})();
_.C("iframes.allow",_.H.nX);_.C("iframes.callSiblingOpener",_.H.QX);_.C("iframes.registerForOpenedSibling",_.H.S5);_.C("iframes.close",_.H.close);_.C("iframes.getGoogleConnectJsUri",_.H.n_);_.C("iframes.getHandler",_.H.Sa);_.C("iframes.getDeferredHandler",_.H.c_);_.C("iframes.getParentInfo",_.H.nN);_.C("iframes.iframer",_.H.BO);_.C("iframes.open",_.H.open);_.C("iframes.openedId_",_.H.e5);_.C("iframes.propagate",_.H.MQ);_.C("iframes.ready",_.H.ready);_.C("iframes.resize",_.H.resize);
_.C("iframes.setGoogleConnectJsVersion",_.H.t7);_.C("iframes.setBootstrapHint",_.H.JH);_.C("iframes.setJsHint",_.H.A7);_.C("iframes.setHandler",_.H.Fc);_.C("iframes.setDeferredHandler",_.H.MH);_.C("IframeBase",$q);_.C("IframeBase.prototype.addCallback",$q.prototype.Pd);_.C("IframeBase.prototype.getMethods",$q.prototype.ny);_.C("IframeBase.prototype.getOpenerIframe",$q.prototype.Hd);_.C("IframeBase.prototype.getOpenParams",$q.prototype.uc);_.C("IframeBase.prototype.getParams",$q.prototype.Ti);
_.C("IframeBase.prototype.removeCallback",$q.prototype.io);_.C("Iframe",tr);_.C("Iframe.prototype.close",tr.prototype.close);_.C("Iframe.prototype.exposeMethod",tr.prototype.qf);_.C("Iframe.prototype.getId",tr.prototype.Aa);_.C("Iframe.prototype.getIframeEl",tr.prototype.Xa);_.C("Iframe.prototype.getSiteEl",tr.prototype.Ib);_.C("Iframe.prototype.openInto",tr.prototype.Gg);_.C("Iframe.prototype.remove",tr.prototype.remove);_.C("Iframe.prototype.setSiteEl",tr.prototype.cg);
_.C("Iframe.prototype.addCallback",tr.prototype.Pd);_.C("Iframe.prototype.getMethods",tr.prototype.ny);_.C("Iframe.prototype.getOpenerIframe",tr.prototype.Hd);_.C("Iframe.prototype.getOpenParams",tr.prototype.uc);_.C("Iframe.prototype.getParams",tr.prototype.Ti);_.C("Iframe.prototype.removeCallback",tr.prototype.io);_.C("IframeProxy",ur);_.C("IframeProxy.prototype.getTargetIframeId",ur.prototype.n0);_.C("IframeProxy.prototype.addCallback",ur.prototype.Pd);_.C("IframeProxy.prototype.getMethods",ur.prototype.ny);
_.C("IframeProxy.prototype.getOpenerIframe",ur.prototype.Hd);_.C("IframeProxy.prototype.getOpenParams",ur.prototype.uc);_.C("IframeProxy.prototype.getParams",ur.prototype.Ti);_.C("IframeProxy.prototype.removeCallback",ur.prototype.io);_.C("IframeWindow",vr);_.C("IframeWindow.prototype.close",vr.prototype.close);_.C("IframeWindow.prototype.onClosed",vr.prototype.VP);_.C("iframes.util.getTopMostAccessibleWindow",_.H.Ua.CN);_.C("iframes.handlers.get",_.H.Iy.get);_.C("iframes.handlers.set",_.H.Iy.set); _.C("iframes.resizeMe",_.H.lR);_.C("iframes.setVersionOverride",_.H.M7);
$q.prototype.send=function(a,b,c){_.H.IR(this,a,b,c)};_.tc.send=function(a,b,c){_.H.IR(_.tc,a,b,c)};$q.prototype.register=function(a,b){var c=this;c.Pd(a,function(a){b.call(c,a)})};_.H.IR=function(a,b,c,d){var e=[];void 0!==c&&e.push(c);d&&e.push(function(a){d.call(this,[a])});a[b]&&a[b].apply(a,e)};_.H.Pr=function(){return!0};_.C("iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.H.Pr);_.C("IframeBase.prototype.send",$q.prototype.send);_.C("IframeBase.prototype.register",$q.prototype.register);
_.C("Iframe.prototype.send",tr.prototype.send);_.C("Iframe.prototype.register",tr.prototype.register);_.C("IframeProxy.prototype.send",ur.prototype.send);_.C("IframeProxy.prototype.register",ur.prototype.register);_.C("IframeWindow.prototype.send",vr.prototype.send);_.C("IframeWindow.prototype.register",vr.prototype.register);_.C("iframes.iframer.send",_.H.BO.send);

}catch(e){_._DumpException(e)}
try{
_.E=_.E||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.E.createElement=function(a){var b;if(!window.document.body||window.document.body.namespaceURI)try{b=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(d){}return b||window.document.createElement(a)};_.E.OC=function(a){var b=_.E.createElement("iframe");
try{var d=["<","iframe"],e=a||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.E.Sx(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var h=_.E.createElement(d.join(""));h&&(!b||h.tagName==b.tagName&&h.namespaceURI==b.namespaceURI)&&(b=h)}catch(l){}d=b;a=a||{};for(var k in a)a.hasOwnProperty(k)&&(d[k]=a[k]);return b};_.E.Yx=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.E.Hha=function(b){return a(b)}})();

}catch(e){_._DumpException(e)}
try{
_.jj=function(){return Math.floor((new Date).getTime()/1E3)};var lj,mj;_.kj=function(a,b){this.wc=a;var c=b||{};this.U3=Number(c.maxAge)||0;this.Uf=c.domain;this.lk=c.path;this.R6=!!c.secure};lj=/^[-+/_=.:|%&a-zA-Z0-9@]*$/;mj=/^[A-Z_][A-Z0-9_]{0,63}$/;_.kj.prototype.read=function(){for(var a=this.wc+"=",b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.kj.prototype.write=function(a,b){if(!mj.test(this.wc))throw"Invalid cookie name";if(!lj.test(a))throw"Invalid cookie value";var c=this.wc+"="+a;this.Uf&&(c+=";domain="+this.Uf);this.lk&&(c+=";path="+this.lk);var d="number"===typeof b?b:this.U3;if(0<=d){var e=new Date;e.setSeconds(e.getSeconds()+d);c+=";expires="+e.toUTCString()}this.R6&&(c+=";secure");window.document.cookie=c;return!0};_.kj.prototype.clear=function(){this.write("",0)}; _.kj.iterate=function(a){for(var b=window.document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
var oj;_.nj=function(a){this.$i=a};oj={};_.nj.prototype.read=function(){if(oj.hasOwnProperty(this.$i))return oj[this.$i]};_.nj.prototype.write=function(a){oj[this.$i]=a;return!0};_.nj.prototype.clear=function(){delete oj[this.$i]};_.nj.iterate=function(a){for(var b in oj)oj.hasOwnProperty(b)&&a(b,oj[b])};
var pj,qj;pj=function(){this.Qa=null;this.key=function(){return null};this.getItem=function(){return this.Qa};this.setItem=function(a,b){this.Qa=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.Qa=null;this.length=0};this.length=0};qj=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}};
_.rj=function(a,b){this.wc=a;this.yI=qj(b)?b||window.sessionStorage:new pj};_.rj.prototype.read=function(){return this.yI.getItem(this.wc)};_.rj.prototype.write=function(a){try{this.yI.setItem(this.wc,a)}catch(b){return!1}return!0};_.rj.prototype.clear=function(){this.yI.removeItem(this.wc)};_.rj.iterate=function(a){if(qj())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var sj=0;64>sj;++sj);_.tj="https:"===window.location.protocol;_.uj=_.tj||"http:"===window.location.protocol?_.kj:_.nj;_.vj=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=(0,window.parseInt)(b,10);if((0,window.isNaN)(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{nd:"S"==a.charAt(0),domain:d,yg:c}};
var wj;wj=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];_.xj=function(a){a=a.toUpperCase();for(var b=0,c=wj.length;b<c;++b){var d=a.split(wj[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.ij,b.TI(a),a=b.Pi().toUpperCase());return a};
_.yj=function(a){if(0!==a.indexOf("GCSC"))return null;var b={He:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.vj(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.nd;return!d&&("U"!==c||e.nd)||d&&!_.tj?b:{He:!0,nd:d,yL:a.substr(1),domain:e.domain,yg:e.yg}};
var zj,Aj,Ej,Fj,Ij;zj=_.Pa();Aj=_.Pa();_.Bj=_.Pa();_.Cj=_.Pa();_.Dj=null;Ej="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");Fj=function(a){this.EG=a;this.NF=null};Fj.prototype.write=function(a){var b=_.Pa(),c=_.Pa(),d;for(d in a)_.Qa(a,d)&&(c[d]=a[d],b[d]=a[d]);d=0;for(var e=Ej.length;d<e;++d)delete c[Ej[d]];a=String(a.authuser||0);d=_.Pa();d[a]=_.E.Uc("#"+_.Gj(c));this.EG.write((0,_.Db)(d));this.NF=b};Fj.prototype.read=function(){return this.NF};
Fj.prototype.clear=function(){this.EG.clear();this.NF=_.Pa()};
_.Hj=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.G.nb(a));var b=window.location.hostname,c=b,d=_.tj;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.qb("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.qb("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,nd:d,yg:b}};
Ij=function(a){if(!a)return null;var b=a.client_id;if(!b)return null;b=_.xj(b);a=_.Hj(a.cookie_policy);return a?!_.tj&&a.nd?(_.qb("WARNING: https cookie_policy set for http domain"),null):["GCSC",a.nd?"E":"U","_",b,"_",a.nd?"S":"H",a.yg].join(""):null};_.Jj=function(a){return a?{domain:a.domain,path:"/",secure:a.nd}:null};_.Kj=function(a){var b=zj[a];b||(b=new Fj(new _.nj(a)),zj[a]=b);return{wh:b,key:a}};
_.Lj=function(a,b){var c=b?Aj:zj,d=b?_.uj:_.rj,e=a&&Ij(a),f=!!e;a&&!a.g_user_cookie_policy&&(d=_.nj,e="token");if(!e)if(!b&&_.Dj)e=_.Dj;else return null;var h=c[e];if(!h){h=_.yj(e);if(!("token"===e||h&&h.He))return null;h=new d(e,_.Jj(h));b||(h=new Fj(h))}c[e]=h;return{wh:h,key:e,EZ:f}};
_.Mj=function(a,b,c){a=a&&"token"!==a?_.Kj(a):_.Lj();if(!a)return null;if(c){c=a.wh;_.Pa();var d=c.EG.read();c=null;try{c=(0,_.Fb)(d)}catch(e){}0==c&&(c=null);d=_.Zi()||"0";d=String(d);c=c&&c[d]}else c=a.wh.read();c&&c.expires_at&&_.jj()>c.expires_at&&(a.wh.clear(),c=null);c&&c.error&&!b&&(c=null);return c};
_.Gj=function(a){var b="";if(!a)return b;for(var c in a)if({}.hasOwnProperty.call(a,c)){var d;d=a[c];if(null!=d){var e=[(0,window.encodeURIComponent)(c),"="];if(d instanceof Array){for(var f=[],h=0;h<d.length;h++)f.push((0,window.encodeURIComponent)(d[h]));e.push(f.join("+"))}else e.push((0,window.encodeURIComponent)(d));d=e.join("")}else d="";d&&(b&&(b+="&"),b+=d)}return b};_.rj.iterate(function(a){var b=_.yj(a);b&&b.He&&(zj[a]=new Fj(new _.rj(a)))}); _.uj.iterate(function(a){zj[a]&&(Aj[a]=new _.uj(a,_.Jj(_.yj(a))))});

}catch(e){_._DumpException(e)}
try{
_.Wi=window.googleapis&&window.googleapis.server||{};
}catch(e){_._DumpException(e)}
try{
_.Nj=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,h;h=e[f];++f)if(0==h.indexOf(d))return h.substr(d.length);return c}}}();
}catch(e){_._DumpException(e)}
try{
_.uc=function(a){var b=_.oa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.wc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.xc=function(a){return"number"==typeof a};_.yc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.zc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Ac=2147483648*Math.random()|0;
}catch(e){_._DumpException(e)}
try{
var Ec;_.Bc=function(a){return/^[\s\xa0]*$/.test(a)};_.Cc=function(a,b){return 0==a.lastIndexOf(b,0)};_.Dc=function(a){return null==a?"":String(a)};Ec=0;_.Fc=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.Gc=function(a){return a[_.sa]||(a[_.sa]=++Ec)};_.Hc=function(a){return"function"==_.oa(a)};
_.Ic=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.Jc=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.t(a))return _.t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.Kc=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Lc=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var l=h[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.Mc=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Nc=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Oc=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.Pc=function(a,b){return 0<=(0,_.Ic)(a,b)};
_.Rc=function(a,b){var c=(0,_.Ic)(a,b),d;(d=0<=c)&&_.Qc(a,c);return d};_.Qc=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Sc=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.uc(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};

}catch(e){_._DumpException(e)}
try{
var Pj,Qj;_.Oj=function(a){this.Cb=a||{cookie:""}};Pj=/\s*;\s*/;_.g=_.Oj.prototype;_.g.isEnabled=function(){return window.navigator.cookieEnabled};_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.ma(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.za)()+1E3*c)).toUTCString();this.Cb.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.Cb.cookie||"").split(Pj),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=this.Ni(a);this.set(a,"",0,b,c);return d};_.g.sf=function(){return Qj(this).keys};_.g.Ud=function(){return Qj(this).values};_.g.isEmpty=function(){return!this.Cb.cookie};_.g.Xb=function(){return this.Cb.cookie?(this.Cb.cookie||"").split(Pj).length:0};_.g.Ni=function(a){return _.ma(this.get(a))};
_.g.Pm=function(a){for(var b=Qj(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.g.clear=function(){for(var a=Qj(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};Qj=function(a){a=(a.Cb.cookie||"").split(Pj);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};_.Rj=new _.Oj("undefined"==typeof window.document?null:window.document);_.Rj.yca=3950;

}catch(e){_._DumpException(e)}
try{
var Sj=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;p=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,q,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),q=1518500249):(m=d^f^k,q=1859775393):60>c?(m=d&f|k&(d|f),q=2400959708):(m=d^f^k,q=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+q+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64;for(;d<c;)if(f[m++]=a[d++],p++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64}function d(){var a=[],
d=8*p;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,p;a();return{reset:a,update:c,digest:d,Pi:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
var Uj=function(a,b,c){var d=[],e=[];if(1==(_.pa(c)?2:1))return e=[b,a],(0,_.Kc)(d,function(a){e.push(a)}),Tj(e.join(" "));var f=[],h=[];(0,_.Kc)(c,function(a){h.push(a.key);f.push(a.value)});c=Math.floor((new Date).getTime()/1E3);e=0==f.length?[c,b,a]:[f.join(":"),c,b,a];(0,_.Kc)(d,function(a){e.push(a)});a=Tj(e.join(" "));a=[c,a];0==h.length||a.push(h.join(""));return a.join("_")},Tj=function(a){var b=Sj();b.update(a);return b.Pi().toLowerCase()};
var Wj;_.Vj=function(a){var b={SAPISIDHASH:!0,APISIDHASH:!0};return a&&(a.OriginToken||a.Authorization&&b[String(a.Authorization).split(" ")[0]])?!0:!1};Wj=function(){var a=_.r.__OVERRIDE_SID;null==a&&(a=(new _.Oj(window.document)).get("SID"));return!!a};
_.Xj=function(a){var b=_.Vi(String(_.r.location.href));if(Wj()){var c=0==b.indexOf("https:")||0==b.indexOf("chrome-extension:"),b=c?_.r.__SAPISID:_.r.__APISID;null==b&&(b=(new _.Oj(window.document)).get(c?"SAPISID":"APISID"));if(b){var c=c?"SAPISIDHASH":"APISIDHASH",d=String(_.r.location.href);return d&&b&&c?[c,Uj(_.Vi(d),b,a||null)].join(" "):null}}return null};
_.Yj={g2:_.Vj,m3:Wj,Y_:function(){var a=null;Wj()&&(a=window.__PVT,null==a&&(a=_.Nj.get("BEAT")));return a},ZD:_.Xj};
}catch(e){_._DumpException(e)}
try{
_.ph=function(a){return(0,window.encodeURIComponent)(String(a))};_.qh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.rh=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.sh=function(a,b,c){if(_.pa(b))for(var d=0;d<b.length;d++)_.sh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.ph(b))}; _.th=function(a,b){for(var c in b)_.sh(c,b[c],a);return a};

}catch(e){_._DumpException(e)}
try{
var bk;bk=function(a,b){var c=_.E.OC({id:a,name:a});c.style.width="1px";c.style.height="1px";c.style.position="absolute";c.style.top="-100px";var d;if(window.navigator){d=window.navigator.userAgent||"";var e=window.navigator.product||"";d=0!=d.indexOf("Opera")&&-1==d.indexOf("WebKit")&&"Gecko"==e&&0<d.indexOf("rv:1.")}else d=!1;c.src=d?"about:blank":b;c.tabIndex=-1;window.document.body.appendChild(c);d&&(c.src=b);return c};
_.ck=function(){function a(){return!!h("auth/useFirstPartyAuthV2")}function b(a,b,c,d){var e=h("proxy");if(c||!e)var e=h("root"),f=h("root-1p")||e,e=e||"https://content.googleapis.com",f=f||"https://clients6.google.com",k=h("xd3")||"/static/proxy.html",e=(c||String(b?f:e))+k;e=String(e);(b=_.E.Uc().jsh||_.Ti.iC.cN())&&(e+=(0<=e.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(b));h("push")&&(e+=(0<=e.indexOf("?")?"&":"?")+"p=1");e+="#parent="+(0,window.encodeURIComponent)(null!=d?String(d):
_.Ti.nb(window.document.location.href));return e+("&rpctoken="+a)}function c(a,b,c,d){var h=e(c,d);l[h]||(c=bk(h,b),_.G.register("ready:"+a,function(){_.G.unregister("ready:"+a);if(!m[h]){m[h]=!0;var b=p[h];p[h]=[];for(var c=0,d=b.length;c<d;++c){var e=b[c];f(e.uo,e.n6,e.fe)}}}),_.G.Hv(h,b),l[h]=c)}function d(a,d){var e=String(2147483647*(0,_.ak)()|0),f=b(e,a,d);_.Hb(function(){c(e,f,a,d)})}function e(a,c){var d=b("",a,c,""),e=k[d];e||(e=_.Zj(),e.update(d),e=e.Pi().toLowerCase(),e+=Math.random(),
k[d]=e);return"apiproxy"+e}function f(a,b,c){var f=void 0,h=!1;if("makeHttpRequests"!==a)throw'only "makeHttpRequests" RPCs are implemented';var k=function(a){if(a){if("undefined"!=typeof f&&"undefined"!=typeof a.root&&f!=a.root)throw"all requests in a batch must have the same root URL";f=a.root||f;h=_.Yj.g2(a.headers)}};if(b)for(var q=0,v=b.length;q<v;++q){var x=b[q];x&&k(x.params)}var J=e(h,f);l[J]||d(h,f);m[J]?_.G.call(J,a,function(a){if(this.f==J&&this.t==_.G.ll(this.f)&&this.origin==_.G.xl(this.f)){var b=
(0,_.Fb)(a);c(b,a)}},b):(p[J]||(p[J]=[]),p[J].push({uo:a,n6:b,fe:c}))}function h(a){return _.D("googleapis.config/"+a)}var k={},l={},m={},p={};return{QK:function(b,c,d){var e=d||"auto";b=b||{};if("none"==e)return b;c=c||window.location.href;d=b.Authorization;var f=b.OriginToken;if(!d&&!f){f=_.Mj(void 0,void 0);!f&&window.gapi.auth2&&"function"==typeof window.gapi.auth2._gt&&(f=window.gapi.auth2._gt());f&&f.access_token&&("oauth2"==e||"auto"==e)&&(d=String(f.token_type||"Bearer")+" "+f.access_token);
if(f=!d)f=(!!h("auth/useFirstPartyAuth")||"1p"==e)&&"oauth2"!=e;if(f&&_.Yj.m3()){if(a()){d=h("primaryEmail");var e=h("appDomain"),f=h("fogId"),k=[];d&&k.push({key:"e",value:d});e&&k.push({key:"a",value:e});f&&k.push({key:"u",value:f});d=_.Yj.ZD(k)}else d=_.Yj.ZD();d&&(c=_.google.vE(c),c=b["X-Goog-AuthUser"]||c,_.Bc(_.Dc(c))&&(!a()||a()&&_.Bc(_.Dc(h("primaryEmail")))&&_.Bc(_.Dc(h("appDomain")))&&_.Bc(_.Dc(h("fogId"))))&&(c="0"),_.Bc(_.Dc(c))||(b["X-Goog-AuthUser"]=c))}d?b.Authorization=d:!1!==h("auth/useOriginToken")&& (f=_.Yj.Y_())&&(b.OriginToken=f)}return b},Tq:f}}();

}catch(e){_._DumpException(e)}
try{
var dk=["appVersion","platform","userAgent"],ek=function(a){if(a&&window.navigator){for(var b=[],c=0;c<dk.length;c++){var d=window.navigator[dk[c]];d&&b.push((0,window.encodeURIComponent)(dk[c])+"="+(0,window.encodeURIComponent)(d))}a["X-ClientDetails"]=b.join("&")}},fk=function(a){return{execute:function(b){var c={};if(a.headers)for(var d in a.headers)Object.prototype.hasOwnProperty.call(a.headers,d)&&(c[d]=a.headers[d]);c=_.ck.QK(c);ek(c);var e={},f=a.urlParams;if(f)for(d in f)Object.hasOwnProperty.call(f,
d)&&(e[d]=f[d]);d=_.D("googleapis.config/developerKey");(d=_.D("client/apiKey",d))&&!e.key&&(e.key=String(d));(d=_.D("client/trace"))&&!e.trace&&(e.trace=String(d));_.ck.Tq("makeHttpRequests",[{key:"googleapisRequest",params:{id:"googleapisRequest",key:"googleapisRequest",clientVersion:"1.0.0-alpha",httpMethod:a.httpMethod||"GET",root:a.root,url:a.url,urlParams:e,headers:c,body:a.body}}],function(a){return function(b){a(b.googleapisRequest.data)}}(b))}}},gk=function(a,b){return function(c){var d=
{};c=c.body;var e=(0,_.Fb)(c),f={};if(e&&e.length)for(var h=0,k=e.length;h<k;++h){var l=e[h];f[l.id]=l}h=0;for(k=b.length;h<k;++h)l=b[h].id,d[l]=e&&e.length?f[l]:e;a(d,c)}},hk=function(a,b){a.transport={name:"googleapis",execute:function(b,d){for(var c=[],f=0,h=b.length;f<h;++f){var k=b[f],l=k.method,m=String(l).split(".")[0],m=_.D("googleapis.config/versions/"+l)||_.D("googleapis.config/versions/"+m)||"v1";c.push({jsonrpc:"2.0",id:k.id,method:l,apiVersion:String(m),params:k.params})}f=fk({httpMethod:"POST",
root:a.transport.root,url:"/rpc?pp=0",headers:{"Content-Type":"application/json"},body:c});f.execute.call(f,gk(d,c))},root:b}},ik=function(a){var b=this.method,c=this.transport;c.execute.call(c,[{method:b,id:b,params:this.rpc}],function(c){c=c[b];c.error||(c=c.data||c.result);a(c)})},jk=function(a,b,c){a={method:a,rpc:b||{}};hk(a,c);a.execute=ik;return a},kk=function(a,b){for(var c=a.split("."),d=function(c){c=c||{};c.groupId=c.groupId||"@self";c.userId=c.userId||"@viewer";return jk(a,c,b)},e=_.r,
f=0,h=c.length;f<h;++f){var k=e[c[f]]||{};f+1==h&&(k=d);e=e[c[f]]=k}if(1<c.length&&"googleapis"!=c[0])for(c[0]="googleapis","delete"==c[c.length-1]&&(c[c.length-1]="remove"),e=_.r,f=0,h=c.length;f<h;++f)k=e[c[f]]||{},f+1==h&&(k=d),e=e[c[f]]=k},lk;for(lk in _.D("googleapis.config/methods"))kk(lk);
_.C("googleapis.newRequest",function(a,b,c){return jk(a,b,c)});_.C("googleapis.newHttpRequest",function(a){return fk(a)});_.C("googleapis.register",function(a,b){kk(a,b)});_.C("googleapis.setUrlParameter",function(a,b){if("trace"!==a)throw Error("F");_.gb("client/trace",b)});_.C("googleapis.setDeveloperKey",function(a){_.gb("googleapis.config/developerKey",a);_.gb("client/apiKey",a)});_.C("googleapis.setVersions",function(a){_.gb("googleapis.config/versions",a)});

}catch(e){_._DumpException(e)}
})(this._);
// Google Inc.
